### ISSUE TITLE
update screenshots to match new ui

### ISSUE THREAD

**Issue by ktravers** [learn-co-curriculum/navigating-curriculum-on-learn#1]
current screenshots are out of date:

<img width="998" alt="screen shot 2015-11-30 at 1 46 41 am" src="https://cloud.githubusercontent.com/assets/8152930/11465151/4431df0a-9704-11e5-8f74-04e1e3993e52.png">

**Comment by frahman5** [comment]
closed by #3

**Comment by frahman5** [comment]
addressed by #3
