### ISSUE TITLE
Problem with moving on to next lesson & Ask A Question

### ISSUE THREAD

**Issue by MC5776** [learn-co-curriculum/navigating-curriculum-on-learn#6]
Hello. Although I've finished every topic in this lesson, I'm unable to continue on to the next, Ruby Basics, Power Interpolation. This lesson continues to show up with a yellow/orange? ring on the drop-down list. When I click on "Ask A Question", a windows does not open so that I may write my question. I'm also unable to launch Nitrous, in spite of not having had any problems in the past. I went from Windows 7 Chrome and Firefox, to Firefox on Mac OS 10.11.4. today, all with the same results, as it doesn't seem to be an OS or browser specific problem. As a programming newbie though, I'm only speculating. I hope that I've posted this in the appropriate place. Thank you for your time, and any help that you may be able to offer. I'm hoping to resolve this before my first group study time tomorrow, 4-5PST.

**Comment by AnnJohn** [comment]
hi @MC5776 sorry for the issue that you're having. The Ask a Question button had some issues but it should be fixed now. 

With regards to technical issues like this, it's best to use the "Ask a Question" tool (but of course understand that you weren't able to access it a few days ago). Also to resolve it faster, filing a bug report also helps. If you hover over your profile pic in Learn, you'll see an option to report a bug. 

This issues space is for problems related specifically to the curriculum, i.e. errors in the test or confusing information. 

Thanks
